### ISSUE TITLE
SUGGESTION: Can you work on a 2022 edition?

### ISSUE THREAD

**Issue by mosesman831** [tejashwikalptaru/csharp-clamAV-antivirus#1]
Hello! @tejashwikalptaru can you work on a 2022 version with updated UI and updated virus database (freshclam)?

**Comment by tejashwikalptaru** [comment]
hey @mosesman831 I have no intention to work on this project anytime soon. Given this is an open-source project, if you need you can update the virus database itself or you are free to change the UI as you please.

**Comment by manm15** [comment]
Can you please send all the plugins you have used because I got a build error when compiling it? Thanks!
