### ISSUE TITLE
The install menu

### ISSUE THREAD

**Issue by YT-Advanced** [tejashwikalptaru/csharp-clamAV-antivirus#3]
Hello, I am interested with your antivirus but I can't find any code of the install menu on source. Can you help me to add it into project
![image](https://user-images.githubusercontent.com/70064328/163703307-97ccb95a-8cc6-4445-9d37-fde71c119491.png)

**Comment by tejashwikalptaru** [comment]
you can use any installer builder for Windows, for example, I have used https://www.advancedinstaller.com/
